linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gosec
    - goimports
    - gocognit
    - misspell
    - gocyclo
    - whitespace
