FROM golang:1.21.4-bookworm AS builder

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

COPY . .

WORKDIR /build/cmd/delete

RUN CGO_ENABLED=0 go build -tags "netgo" -installsuffix netgo -ldflags="-s -w -extldflags \"-static\"" -trimpath -o ./delete

FROM debian:bookworm-20231009-slim

RUN apt-get update && apt-get install --no-install-recommends -y ca-certificates=20230311 && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN useradd -m nonroot

COPY --from=builder /build/cmd/delete /

USER nonroot

ENTRYPOINT ["./delete"]
