FROM golang:1.24.2-bookworm AS builder

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

COPY . .

WORKDIR /build/cmd/delete

RUN go build -ldflags '-w -s' -trimpath -o ./delete

FROM debian:bookworm-20250407-slim

RUN apt-get update && apt-get install --no-install-recommends -y ca-certificates && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN useradd -m nonroot

COPY --from=builder /build/cmd/delete /

USER nonroot

ENTRYPOINT ["./delete"]
