services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: ranking
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ranking" ]
      interval: 1s
  pgweb:
    image: sosedoff/pgweb:0.14.1
    container_name: pgweb
    ports:
      - "8080:8081"
    links:
      - postgres:postgres
    environment:
      - DATABASE_URL=postgres://user:password@postgres:5432/ranking?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
