FROM golang:1.24.2-bookworm AS builder

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

COPY . .

WORKDIR /build/cmd/standard-writer

RUN go build -ldflags '-w -s' -trimpath -o ./writer

FROM debian:bookworm-20250407-slim

RUN apt-get update && apt-get install --no-install-recommends -y ca-certificates && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN useradd -m nonroot

COPY --from=builder /build/cmd/standard-writer/writer /
COPY --from=builder /build/standard-writer.sh /

RUN chmod +x /standard-writer.sh

USER nonroot

ENTRYPOINT ["./standard-writer.sh"]
