FROM golang:1.21.4-bookworm AS builder

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

COPY . .

WORKDIR /build/cmd/api-server

RUN go build -ldflags="-s -w -extldflags \"-static\"" -trimpath -o ./server

FROM gcr.io/distroless/base-debian12

COPY --from=builder /build/cmd/api-server/server /

USER nonroot

ENTRYPOINT ["./server"]
