name: Build and Push Docker Image to GitHub Container Registry

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  test-and-lint:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.2'

      - name: Run linter
        run: make lint

      - name: Run tests
        run: make test

  build-and-push:
    needs: test-and-lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for git tags
        id: check-tags
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "tag=latest" >> "$GITHUB_OUTPUT"
          else
            echo "tag=${{ github.ref_name }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile-standard-writer
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/top-sites-ranking-api:latest
            ghcr.io/${{ github.repository_owner }}/top-sites-ranking-api:${{ steps.check-tags.outputs.tag }}
