name: Test and Lint project

on:
  pull_request:

jobs:
  test-and-lint:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.1.5

      - name: Run tests
        run: make test
